server:
  port: 10099
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.138.22.185:3306/yelp?useSSL=false&serverTimezone=UTC
    username: root
    password: 2000528gmy
  redis:
    host: 43.138.22.185
    port: 26379
    password: 2000528gmy
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug


# 排除拦截的路径
yelp:
  exclude-path: /user/code,/user/login,/blog/host,/shop/**,/shop-type/**,/voucher/**
  exclude: 12
